pipeline {
    agent any
    stages {
        stage('Cleanup Old Image') {
            steps {
                bat 'docker rmi notification-service:latest || ver > nul'
            }
        }
        stage('Build Artifact') {
            steps {
                dir('notification-service') {
                    bat 'mvn package'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('notification-service') {
                    bat 'docker build -t notification-service:latest .' 
                }
            }
        }
    }
}