CREATE DATABASE IF NOT EXISTS authenticationservicedb;
CREATE DATABASE IF NOT EXISTS inventoryservicedb; 
CREATE DATABASE IF NOT EXISTS notificationservicedb; 
CREATE DATABASE IF NOT EXISTS orderservicedb; 
CREATE DATABASE IF NOT EXISTS billingservicedb;
USE authenticationservicedb;
CREATE TABLE IF NOT EXISTS roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);
INSERT INTO roles(name) VALUES('ROLE_CUSTOMER');
INSERT INTO roles(name) VALUES('ROLE_WAREHOUSE_MANAGER');
INSERT INTO roles(name) VALUES('ROLE_FINANCE_OFFICER');