pipeline {
    agent any
    stages {
        stage('Cleanup Old Image') {
            steps {
                bat 'docker rmi eureka-server:latest || ver > nul'
            }
        }
        stage('Build Artifact') {
            steps {
                dir('service-registry') {
                    bat 'mvn package'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('service-registry') {
                    bat 'docker build -t eureka-server:latest .' 
                }
            }
        }
    }
}